# This is a basic workflow to help you get started with Actions

name: Build and Deploy to Web App for Containers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

       # Authenticate a Service Principal to deploy to your Web App
      - name: Azure Service Principal Authentication
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a set of commands using the runners shell
      # Use docker login to log into ACR 
      - name: Docker login to ACR
        run: az acr login -n ${{ secrets.CONTAINER_NAME }}

     # Build and push your image to Azure Container Registry 
      - name: Build and Push container to ACR
        run: |
          docker build --file=Dockerfile -t ${{ secrets.CONTAINER_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }} .
          docker push shayne.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }}  

      - name: Deploy to Azure Web App for Containers
        # You may pin to the exact commit or the version.
        run: az webapp config container set -n ${{ secrets.APP_NAME }} -g ${{ secrets.APP_NAME }} --docker-custom-image-name shayne.azurecr.io/${{ secrets.IMAGE_NAME }}:${{ github.sha }} --docker-registry-server-url https://${{ secrets.CONTAINER_REGISTRY_NAME }} 

        
        
